name: main

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  validate:
    uses: ./.github/workflows/validate.yml

  upload:
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  deploy:
    needs: [test, validate, upload]
    concurrency:
      group: deploy-main
      cancel-in-progress: false
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
