name: main

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  validate:
    uses: ./.github/workflows/validate.yml

  upload:
    uses: ./.github/workflows/upload.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}
    permissions:
      id-token: write
      contents: read

  deploy:
    needs: [test, validate, upload]
    concurrency:
      group: deploy-main
      cancel-in-progress: false
    uses: ./.github/workflows/deploy.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}
      DATA_BUCKET: ${{ secrets.DATA_BUCKET }}
      PERMISSIONS_BOUNDARY_ARN: ${{ secrets.PERMISSIONS_BOUNDARY_ARN }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_STATE_OBJECT_KEY: ${{ secrets.TF_STATE_OBJECT_KEY }}
    permissions:
      id-token: write
      contents: read
