name: PR

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  validate:
    uses: ./.github/workflows/validate.yml
