name: "sast"

on:
  pull_request: {}
  schedule:
    - cron: '36 9 * * *'

jobs:
  sast:
    name: sast
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download Go packages
        shell: bash
        run: |
          go get ./...

      - name: golangci-lint # https://github.com/golangci/golangci-lint
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/golangci/golangci-lint/releases/latest | jq -r ".tag_name" | cut -c2-)
          echo "Latest version is $VERSION"
          curl -O -L "https://github.com/golangci/golangci-lint/releases/download/v${VERSION}/golangci-lint-${VERSION}-linux-amd64.tar.gz"
          tar -xvzf "golangci-lint-${VERSION}-linux-amd64.tar.gz" -C "$(go env GOPATH)/bin" --strip-components 1 "golangci-lint-${VERSION}-linux-amd64/golangci-lint"
          chmod +x "$(go env GOPATH)/bin/golangci-lint"
          golangci-lint --version
          golangci-lint run --timeout=3m

      - name: govulncheck
        shell: bash
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: gosec # https://github.com/securego/gosec
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/securego/gosec/releases/latest | jq -r ".tag_name" | cut -c2-)
          echo "Latest version is $VERSION"
          curl -O -L "https://github.com/securego/gosec/releases/download/v${VERSION}/gosec_${VERSION}_linux_amd64.tar.gz"    
          tar -xvzf "gosec_${VERSION}_linux_amd64.tar.gz" -C "$(go env GOPATH)/bin" "gosec"
          chmod +x "$(go env GOPATH)/bin/gosec"
          gosec ./...

      - name: nancy # https://github.com/sonatype-nexus-community/nancy
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/sonatype-nexus-community/nancy/releases/latest | jq -r ".tag_name" | cut -c2-)
          echo "Latest version is $VERSION"
          curl -O -L "https://github.com/sonatype-nexus-community/nancy/releases/download/v${VERSION}/nancy-v${VERSION}-linux-amd64"
          mv "nancy-v${VERSION}-linux-amd64" "$(go env GOPATH)/bin/nancy"
          chmod +x "$(go env GOPATH)/bin/nancy"
          go list -json -deps ./... | nancy sleuth --exclude-vulnerability CVE-2024-8421
