name: SAST
on:
  pull_request: {}
  schedule:
    - cron: "35 9 * * *"

jobs:
  sast:
    permissions:
      contents: read
    uses: ockendenjo/actions/.github/workflows/sast.yaml@76e60c05f85023793893a7e8fd0cc3a85a8c80cb # main
